# -*- mode: python ; coding: utf-8 -*-
import sys


a = Analysis(
    ['src/Papyrus.py'],
    pathex=['src'],
    binaries=[],
    datas=[
        ('assets', 'assets'),
        ('src/papyrus', 'papyrus'),
        ('src/papyrus_api', 'papyrus_api'),
        ('src/ai', 'ai'),
        ('src/mcp', 'mcp'),
        ('src/logger.py', '.'),
    ],
    hiddenimports=[
        'papyrus',
        'papyrus.core',
        'papyrus.core.cards',
        'papyrus.data',
        'papyrus.data.database',
        'papyrus.data.notes_storage',
        'papyrus.data.storage',
        'papyrus.data.relations',
        'papyrus.data.progress',
        'papyrus.paths',
        'papyrus.resources',
        'papyrus.integrations',
        'papyrus.integrations.ai',
        'papyrus.integrations.file_watcher',
        'papyrus.integrations.logging',
        'papyrus.integrations.mcp',
        'papyrus.integrations.obsidian',
        'papyrus_api',
        'papyrus_api.main',
        'papyrus_api.deps',
        'papyrus_api.routers',
        'papyrus_api.routers.cards',
        'papyrus_api.routers.review',
        'papyrus_api.routers.notes',
        'papyrus_api.routers.vault',
        'papyrus_api.routers.search',
        'papyrus_api.routers.ai',
        'papyrus_api.routers.data',
        'papyrus_api.routers.relations',
        'papyrus_api.routers.progress',
        'papyrus_api.routers.logs',
        'papyrus_api.routers.update',
        'papyrus_api.routers.markdown',
        'papyrus_api.routers.mcp',
        'ai',
        'ai.config',
        'ai.provider',
        'ai.tools',
        'ai.tool_manager',
        'ai.sidebar_v3',
        'mcp',
        'mcp.server',
        'mcp.vault_tools',
        'logger',
        'uvicorn',
        'uvicorn.logging',
        'uvicorn.loops',
        'uvicorn.loops.auto',
        'uvicorn.protocols',
        'uvicorn.protocols.http',
        'uvicorn.protocols.http.auto',
        'uvicorn.lifespan',
        'uvicorn.lifespan.on',
        'fastapi',
        'fastapi.middleware',
        'fastapi.middleware.cors',
        'pydantic',
        'starlette',
        'requests',
        'watchdog',
        'markdown_it',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='Papyrus',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=['assets/icon.ico'] if sys.platform == 'win32' else None,
)
